# Node.js base image ব্যবহার করো
FROM node:18

# কন্টেইনারে কাজ করার ডিরেক্টরি তৈরি করো
WORKDIR /app

# main.js কপি করো
COPY main.js .

# কন্টেইনার চালানোর সময় কি কমান্ড রান করবে
CMD ["node", "main.js"]
